###################
### SIMULATIONS ###
###################

## LARGE SAMPLE SIZE
# sample size (normal n=1000, small n=100)
n=1000
# to create family structure (g=20) or not (g=1)
g=1
# hacks to use "real" data scripts on simulations
name="sim-n$n-k10-f0.1-s0.5-g$g"
# run shared steps
. main-sim.bash


## SMALL SAMPLE SIZE
# sample size (normal n=1000, small n=100)
n=100
# to create family structure (g=20) or not (g=1)
g=1
# hacks to use "real" data scripts on simulations
name="sim-n$n-k10-f0.1-s0.5-g$g"
# run shared steps
. main-sim.bash


## FAMILY STRUCTURE
# sample size (normal n=1000, small n=100)
n=1000
# to create family structure (g=20) or not (g=1)
g=20
# hacks to use "real" data scripts on simulations
name="sim-n$n-k10-f0.1-s0.5-g$g"
# run shared steps
. main-sim.bash


######################
### REAL GENOTYPES ###
######################

# creates a table other scripts might use, especially when creating figures, for consistent human-facing naming, and loops across all datasets
# writes data/datasets.txt
Rscript real-00-datasets.R


# shared by R script calls further below
name='HoPacAll_ld_prune_1000kb_0.3_maf-0.01'
DATA_DIR='/home/viiia/dbs/humanOrigins'
# run shared steps (real, tree simulations, and 4th degree relatives removed)
. main-real.bash


# version for HGDP WGS
name='hgdp_wgs_autosomes_ld_prune_1000kb_0.3_maf-0.01'
DATA_DIR='/home/viiia/dbs/hgdp_wgs'
# run shared steps
. main-real.bash


# version for TGP
name='tgp-nygc-autosomes_ld_prune_1000kb_0.3_maf-0.01'
DATA_DIR='/home/viiia/dbs/tgp-nygc'
# run shared steps
. main-real.bash


###############
### GLOBALS ###
###############

# cross-dataset analyses, including all of: sim, real, and real-sim
# this sequence also creates all of the main figures/tables in order of appearance

# reports actual dimensions (n_ind, m_loci, K, and m_causal) used in all datasets
# (validates every replicate too! for m_causal compares both FES and RC!)
# writes data/dimensions.txt
time Rscript real-14-dimensions.R
# 0m24.674s viiiaR5

# MAF plot code
time Rscript real-17-mafs-plot.R
# 0m13.937s viiiaR5

# popkin kinship plots
# includes data generated by MAF script above
time Rscript all-01-kinship.R
# 30s ideapad

# a simple figure that illustrates the methods
# (uses data from "Admix. Large sim." only)
time Rscript sim-10-measures-fig.R 2
# Inflation factor: pca-plink-pure: 2.96003533785624
# Inflation factor: gcta: 0.87992175683473
# Inflation factor: gcta: 0.984541944592377

# main statistical evaluations between methods
time Rscript real-13-stats.R

# final plot gathers all three datasets into a single multipanel figure
time Rscript real-15-plots-big.R
time Rscript real-15-plots-big.R --fes
time Rscript real-15-plots-big.R --real
time Rscript real-15-plots-big.R --real --fes
time Rscript real-15-plots-big.R --real_sim
time Rscript real-15-plots-big.R --real_sim --fes

# calculages popkin and eigensoft eigenvectors, calculates TW stats, makes plot
time Rscript all-02-eigen.R
# 30m14.103s viiiaR5 first time

# a comparison of RMSD and lambda across ALL datasets (including FES and RC traits)
# this version that fits top half only (makes most sense for our goal of talking mostly about inflation)
time Rscript real-11-inflation-across-datasets.R
# model fit:
# rmsd ~ a * (lambda^b - 1) / (lambda^b + 1)
#         a         b 
# 0.5629478 0.6208654 
# threshold map (sigmoidal): lambda = 1.05, RMSD = 0.00853
# Inverse threshold map (sigmoidal): RMSD = 0.01, lambda = 1.06

# look at kinship distributions in real and simulated datasets
time Rscript all-03-king.R

# calculate dimensions table for this subset separately
time Rscript king-00-dimensions.R

# make AUC/RMSD plot and stats tests for the limited king-cutoff test
time Rscript king-01-rmsd-auc-plot.R
